### ISSUE TITLE
can't activate 3D acceleration

### ISSUE THREAD

**Issue by boistordu** [hyperbox/hyperbox#10]
Hi,

seems that I can't activate 3D acceleration but I can do it on virtualbox.... seems to at least. it's with the intel chipset but the correct drivers of intel are installed and virtualbox works with intel for 3D acceleration so....

**Comment by maxidor** [comment]
Couple a question to make sure we fully understand your issue:

1. By "can't activate", which one do you mean:
  1. The setting is not saved
  2. You get an error while trying to create/edit a VM config with 3D acceleration
  3. You cannot start a VM which has 3D acceleration enabled

2. And by "I can do it on VirtualBox", which do you mean:
  1. Using the GUI, I can start the exact same machine with the same configuration
  2. Using the GUI, I can start another machine with the same configuration
  3. Using VBoxManage, I can start the same machine with the same configuration in GUI mode
  4. Using VBoxManage, I can start another machine with the same configuration in GUI mode
  5. Using VBoxManage, I can start the same machine with the same configuration in Headless mode
  6. Using VBoxManage, I can start another machine with the same configuration in Headless mode

**Comment by boistordu** [comment]
Yeah sorry I should have been more careful in my post but i was a bit in a rush. So sorry about that.

so when I try to activate the settings and then save the configuration of the VM it tells me failed.

If I try to create a virtual machine in virtualbox with the GUI, it accept the settings without complaining. I don't have tested yet with VBoxManage but I can try tomorrow if you want. 

And if you  do a little google search you will see that virtualbox should accept intel graphic chipset and if it does not it is considered as a bug. execpt on mint which is not compatible apparently. Maybe other systems too?

anyway my host is a ubuntu 16.04.1 server with xfce4 interface on it. I wanted to activate on windows guest as win7 . but with other guests it doesn't seem to activate itself either. 
I can try to diagnose further if you want tomorrow. but if you have some leads, I'm all ears open.

**Comment by maxidor** [comment]
After saving the configuration, you should have a related task in the hyperbox client window at the bottom.
Can you double click on that task and let me know the exact error message displayed there? it's the last text field in the window.

**Comment by boistordu** [comment]
I don't have much time to test it right now and it won't be very useful because the disk of the vm is not in a great format for windows (.QED here in place of VMDK) ....
shit apprently it doesn't do it anymore at the saving of the VM now it does it at the start of the VM but that s more of a VBoxManage message I guess so I will do more testing tomorrow if you don't mind to see if virtualbox accept the configuration and if hyperbox return an error. 
I will post here tomorrow. sorry to disturb you about that :) 
"This VM was configured to use 3D acceleration. However, the 3D support of the host is not working properly and the VM cannot be started. To fix this problem, either fix the host 3D support (update the host graphics driver?) or disable 3D acceleration in the VM settings (VERR_NOT_AVAILABLE)"

**Comment by maxidor** [comment]
You're not disturbing anything, thank you for taking the time to report this issue!
No rush to give the extra info, whenever is best for you.

**Comment by boistordu** [comment]
So I'm just working with my test right now. I've just create a vm with virtualbox GUI with 3D acceleration, right now I'm just installing windows right now. But anyway if the 3D acceleration wasn't working, it wouldn't start it at all since I think the verification of the possibility of 3D acceleration is made before launching the VM right?

**Comment by boistordu** [comment]
well I don't really know how to test it inside a vm but anyway i've installed a windows 7vm and the 3D acceleration tells me its activated while I run the vm ... so should I try to create same vm with vboxmanage?

**Comment by maxidor** [comment]
After checking with the VirtualBox devs, 3D Acceleration would only be supported in a proper GUI user session.
Trying to start a VM with 3D Acceleration enabled through a software like Hyperbox which runs as a service without any UI/X server configuration will cause the VM to fail.
They don't plan to support it either, so that's it in term of "official" answer.

On the unofficial side, if you run Hyperbox under Linux, you can always include a DISPLAY env variable in the init.d script and point to a properly configure X Server and see if that works.

**Comment by boistordu** [comment]
mmmmh okey now I understand, it has to have a display ok ... understood  
thanks nayway
