### ISSUE TITLE
feature requested if it does not exist

### ISSUE THREAD

**Issue by boistordu** [hyperbox/hyperbox#11]
Is it possible or would it be possible to transfer a VM to hyperbox and make it appear on the GUI of virtualbox?

**Comment by maxidor** [comment]
Yes it is. Right click on the server on the left, go into the `Machine` menu and choose `Register`.
You can then choose the .vbox file of the VM for it to be registered.

**BEWARE:** VirtualBox is made to be a per-user process, meaning that if the VM is already running under another session, VirtualBox (and Hyperbox) will not be able to see it and it will create a conflict.
Be sure that any VM which is used by Hyperbox are actually dedicated and not share with other users/processes.

**Comment by maxidor** [comment]
Oh you want to transfer a VM from hyperbox!
To do that:
- Stop the VM in Hyperbox
- Unregister the VM, without deleting it
- Fix permissions on the VM folder so the target user(s) have at least ownership and read access
- Register the VM in VirtualBox using `Machine > Add...` or `Ctrl+A` in the main GUI

**Comment by boistordu** [comment]
wait wait I think we need to understand each other first :p 
I want to be able to have on the GUI list of virtualbox under USERTEST for example the name of some of my VMs. And so, be able to launch the VM with this user in place of hyperbox (because I would need to activate 3D acceleration for example) . is that solution 1 or solution 2? 
and is It possible to have the same VM in both lists? the one from hyperbox and the one from GUI of virtualbox under the USERTEST?

**Comment by maxidor** [comment]
If you want to be able to start it from both, the only step you need to skip is to unregister the VM in Hyperbox.
But you'll need to fix permissions each time you switch launcher for the concerned user.
The VM state will not be known on the "other side".

This use case is not what Hyperbox is designed for, since it builds on VirtualBox isolating VMs at the user level. So be cautious.

**Comment by boistordu** [comment]
mmmmh right I did forget about the general usecase of hyperbox. OKey so I will choose carefully the VM I want to run with a specific user in place of sharing the VM between both system. thanks :)
