### ISSUE TITLE
sharing internal network between hyperbox and virtualbox

### ISSUE THREAD

**Issue by boistordu** [hyperbox/hyperbox#12]
does the two shared the same internal network or is it the same principle than VMs?

**Comment by maxidor** [comment]
Same principle than VMs - internal network is only in memory of the VirtualBox service (VBoxSVC) which is per-user.

If you want a way for VMs to communicate, you can use Bridged (will work) and possibly Host-Only mode (never tried that)

**Comment by FedgeNo** [comment]
Your question isn't really clear to me but if you're talking about manually starting some VMs and having others managed by Hyperbox, you could probably just run the ones you're starting manually under the hyperbox user. If you're going to use Hyperbox you might as well have it control all of your VirtualBox VMs, though. That's what it's for.

**Comment by boistordu** [comment]
mmmmh shit that doesn't add up with what I try to do. I don't need to activate 3D acceleration on my windows server 2016 which organise the DHCP server and NAT . but I at least need the 3D acceleration of one of the VM. I will see what it does with phpvirtualbox. I can understand that technically it's impossible to make a internal subnet linked between 2 different user but it seems a bit a pity.

**Comment by maxidor** [comment]
@boistordu Isolating by user is simply how VirtualBox was designed, on purpose, so it's not a system-level hypervisor but a user-level hypervisor.

Enforcing all VMs to run under a single security context via Hyperbox is simply restricting this to fit another model, but that only works if that restriction is followed.

I think the simple answer here is that Hyperbox might not be the right tool for whatever you want to achieve.
