### ISSUE TITLE
Connecting to an existing hypervisor suceed , but I cannot see already existing vms

### ISSUE THREAD

**Issue by creativeprogramming** [hyperbox/hyperbox#2]
I managed to install server and client and connection worked, also adding hypervisor via xpcom.

But it only allows me to create/register vm. Is there a way to autodetect running vms?

**Comment by maxidor** [comment]
VirtualBox use a per-user VM registration scheme, which means each user 
will only see the VM registered under his profile, but won't see if the 
VMs are already running potentially.
It is therefore very important VMs are not shared between users and not 
tried to be started from several views.

If all your VMs are already under a specific user account and what to 
keep using that one, edit the RUNAS variable into /etc/init.d/hboxd and 
put the user you prefer.
Else, register all the VMs under the current user.

**Comment by creativeprogramming** [comment]
thanks for the clarification, very appreciated. Keep going, great work!
