### ISSUE TITLE
Connection to remote server over SSH tunnel

### ISSUE THREAD

**Issue by jumpingfella** [hyperbox/hyperbox#21]
Hello,
I've been trying to setup connection with remote server over ssh, forwarding ports:
ssh -L 45612:127.0.0.1:45612 -N myuser@remote-server

This doesn't work, UI shows "Connecting" only without any clues on what's wrong. I didn't find anything in the doc on the subject. 

My server is headless, and I don't want to install X-Windows there, thought port forwarding would be the way to go.

**Comment by maxidor** [comment]
On the client side, did you configure the server with 127.0.0.1 as host?

**Comment by jumpingfella** [comment]
Yes, I did.

**Comment by maxidor** [comment]
Just to clarify: SSH port forward is supported and is expected to work.

Can you check the following please:
- hyperbox server is actually running: `ps aux | grep hboxd`
- it is listening on 45612: `netstat -lnp | grep 45612`
- you can actually connect to the port via SSH forward: `nc -vz 127.0.0.1 45612`

Please post the output of each command. If everything seems good, also please post the hboxd.log which is by default located at `/opt/hboxd/log/hboxd.log`

**Comment by jumpingfella** [comment]
1. 16156  0.1  0.2 7819920 293412 ?      Sl   14:33   0:25 java -cp /opt/hboxd/bin/*:/opt/hboxd/lib/* -Xmx75m -Xss2048k io.kamax.hboxd.HyperboxHeadless
2. tcp6       0      0 :::45612                :::*                    LISTEN      16156/java 
3. Connection to 127.0.0.1 45612 port [tcp/*] succeeded!

2017.08.01-14:33:11.679 |      Info | -------> Hyperbox is running <-------
2017.08.01-16:21:49.397 |      Info | Conn #1 127.0.0.1 connected.
2017.08.01-16:21:53.696 |      Info | Conn #1 has disconnected.
2017.08.01-16:21:53.696 |   Warning | Client ID #1 (127.0.0.1:45652) did not close its sessio
n before disconnecting, cleaning up
2017.08.01-18:15:22.756 |      Info | Conn #2 127.0.0.1 connected.
2017.08.01-18:15:22.822 |      Info | Conn #2 has disconnected.
2017.08.01-18:15:22.822 |   Warning | Client ID #2 (127.0.0.1:45846) did not close its sessio
n before disconnecting, cleaning up

I must note that these 2 are my manual connection attempts via telnet to 45612 port

**Comment by maxidor** [comment]
Looking good so far. Could you show the client log for that session? It is located in `<HOME>/.hbox/log/hbox.log`.

Finally, I am not sure the issue is actually related to SSH forwarding. If you have a mean to test a direct connection, that would be great!

**Comment by jumpingfella** [comment]
Here's client log:

2017.08.02-09:40:21.421 |      Info | Checking for update at http://kamax.io/hbox/update/fresh?v=0.0.13
2017.08.02-09:40:21.772 |      Info | No update was found
2017.08.02-09:41:04.475 |      Info | Changed Server #null object state to Connecting
2017.08.02-09:41:04.577 |      Info | Kryonet Connector state: Starting
2017.08.02-09:41:04.583 |      Info | Backend Init Sequence started
2017.08.02-09:41:04.967 |      Info | Backend Init Sequence completed
2017.08.02-09:41:04.969 |      Info | Kryonet Connector state: Started
2017.08.02-09:41:17.298 |      Info | Got exit signal from user
2017.08.02-09:41:17.302 |      Info | Changed Server #null object state to Disconnecting
2017.08.02-09:41:17.302 |      Info | Changed Server #null object state to Disconnected
2017.08.02-09:41:17.422 |      Info | Exiting

**Comment by jumpingfella** [comment]
I can't test direct connection, unfortunately. 

I don't know what protocol you're using for communication, but it looks like that only SSH tunnel is not enough.

**Comment by maxidor** [comment]
Let's try to increase the log level and have it run from a console.
Please start the client the following way (replace the path if needed):
```
export HBOX_LOG_LEVEL=Tracking
export HBOX_LOG_FILE=none
/opt/hboxc/hyperbox
```
Then try to connect to your server, and wait for several minutes if needed, until you have some kind of error message. If you still don't after 5 min (check the timestamp), then close the client.

Post the log output here after using the code formatting please.

**Comment by jumpingfella** [comment]
```
2017.08.02-17:53:48.725 |     debug | Core-EvMgr | Thread | Processing Event ConnectorStateChangedEvent: Connect
or thor state changed to Connecting @ Wed Aug 02 17:53:48 CEST 2017
2017.08.02-17:53:48.725 |     debug | GUI-EvMgr | Thread | Processing Event ConnectorStateChangedEvent: Connecto
r thor state changed to Connecting @ Wed Aug 02 17:53:48 CEST 2017
2017.08.02-17:53:48.751 |      Info | Changed Server #null object state to Connecting
2017.08.02-17:53:48.812 |     debug | SwingWorker-pool-10-thread-2 | ClassManager | _Backend providers took 1 ms
 to find
2017.08.02-17:53:48.833 |      Info | Kryonet Connector state: Starting
2017.08.02-17:53:48.847 |     debug | Core-EvMgr | Thread | Processing Event BackendStateEvent: Backend ID Kryon
et changed state to Starting @ Wed Aug 02 17:53:48 CEST 2017
2017.08.02-17:53:48.847 |     debug | GUI-EvMgr | Thread | Processing Event BackendStateEvent: Backend ID Kryone
t changed state to Starting @ Wed Aug 02 17:53:48 CEST 2017
2017.08.02-17:53:48.847 |      Info | Backend Init Sequence started
2017.08.02-17:53:48.847 |     debug | SwingWorker-pool-10-thread-2 | KryonetClientBack | Trying to get setting k
ryonet.net.buffer.write with default value 1838400
2017.08.02-17:53:48.847 |     debug | SwingWorker-pool-10-thread-2 | KryonetClientBack | Trying to get setting 1
638400 with default value 1638400
2017.08.02-17:53:49.111 |      Info | Backend Init Sequence completed
2017.08.02-17:53:49.112 |      Info | Kryonet Connector state: Started
2017.08.02-17:53:49.112 |     debug | Core-EvMgr | Thread | Processing Event BackendStateEvent: Backend ID Kryon
et changed state to Started @ Wed Aug 02 17:53:49 CEST 2017
2017.08.02-17:53:49.112 |     debug | GUI-EvMgr | Thread | Processing Event BackendStateEvent: Backend ID Kryone
t changed state to Started @ Wed Aug 02 17:53:49 CEST 2017
2017.08.02-17:53:49.112 |     debug | Core-EvMgr | Thread | Processing Event BackendConnectionStateEvent: Backen
d ID Kryonet changed connection state to Connecting @ Wed Aug 02 17:53:49 CEST 2017
2017.08.02-17:53:49.112 |     debug | GUI-EvMgr | Thread | Processing Event BackendConnectionStateEvent: Backend
 ID Kryonet changed connection state to Connecting @ Wed Aug 02 17:53:49 CEST 2017
2017.08.02-18:01:22.851 |      Info | Got exit signal from user
2017.08.02-18:01:22.852 |   verbose | Changing Core State to Stopping
2017.08.02-18:01:22.852 |     debug | Core-EvMgr | Thread | Processing Event CoreStateEvent: Event ID CoreState 
occured @ Wed Aug 02 18:01:22 CEST 2017
```

**Comment by maxidor** [comment]
Very odd, I don't even see any network level entries, which means it's stuck for some reason.
I'll provide you with a debug build within two days which should, hopefully, help pint-point where the issue is.

**Comment by maxidor** [comment]
@jumpingfella Could you please try with [this version](https://kamax.io/hbox/hbox-client-0.0.13-11-gbc11cea-dirty-linux_x64.run) please? We totally refactored the build system which might have removed some incompatibilities.

**Comment by jumpingfella** [comment]
Alright, managed to try it today, looks better. State: connected, protocol 0.0.12
However, Hypervisor shows state: Disconnected. That's probably because of differences of class versions on backend and frontend now. 

It also shows list of modules now. 
But no VMs, unfortunately.

**Comment by maxidor** [comment]
Here is the equivalent server installer: [hbox-server-0.0.13-5-ge90e199-linux_x64.run](https://kamax.io/hbox/hbox-server-0.0.13-5-ge90e199-linux_x64.run)

For the Hypervisor being disconnected, that's because you need to configure it the first time - there is no autodiscovery and connect at this point. you can follow the [First Launch](https://kamax.io/hbox/manual/#il-fl) section of the user manual.

As for the VMs, you will need to register them. Hyperbox runs under its own user and VirtualBox isolates VMs per security context (e.g. user). Feel free to move the VMs from any user to the hypervisor user home directory, set the right permissions (replace the owner) and then register them.
The important part is that VMs managed by Hyperbox should not be shared with other accounts as it could lead to a corruption issue.
