### ISSUE TITLE
Support for VirtualBox 5.2

### ISSUE THREAD

**Issue by 3si2icann** [hyperbox/hyperbox#24]
After upgrading virtualbox from 5.1.28 to 5.2.0, Hyperbox 0.0.13 fails to connect to hypervisor, looks like new versions of connectors needed.

**Comment by maxidor** [comment]
Indeed, I am currently working on it - it will be out very soon!

**Comment by maxidor** [comment]
This was delayed to 5.2.2 due to a known bug. Now that it's out, will get it done!

**Comment by d-petrovich** [comment]
Any news when 5.2.6 vbox will be supported ?

**Comment by maxidor** [comment]
Sorry this is taking us so long, this did not fell out of our radar. Will be done by the end of the month without failure. 3rd time's the charm!

**Comment by paykashcoin** [comment]
I would also like to see 5.2.6 support. Please keep us posted @maxidor

**Comment by maxidor** [comment]
It's out! See https://github.com/hyperbox/hyperbox/releases/tag/0.0.14
