### ISSUE TITLE
Include scripts to create forks (incl. submodules) in Github

### ISSUE THREAD

**Issue by JaimeChavarriaga** [hyperbox/hyperbox#29]
Currently, `hyperbox` includes scripts such as `init`, `status` and `update` that works with the main repositories. However, because the project uses multiple git submodules, the project may include scripts to support creating forks of all the repositories in Github. Note that any contribution may require to provide pull requests for one or more repositories.

The project may (1) include scripts to create the forks and (2) provide instructions for people interested on contributing to the project.

**Comment by maxidor** [comment]
> (1) include scripts to create the forks

As outlined in your related PR, I think the scripts need to have a high added value first, but...

> (2) provide instructions for people interested on contributing to the project

I will make an official stance here by saying this project needs a full rewrite. It has been done years ago and there is a whole set of choices which I would no longer consider good, or appropriate.
Also, this involved a lot of research and I believe a fresh start is in order.

Therefore, I will say that for now, let's not promote contributions until such rewrite happen (it is planned, but no ETA for now). VBox 6.0 coming out make it a good time also.

All in all, yes but no - let's hold off on this I think.
