### ISSUE TITLE
Create a Contributing Guide

### ISSUE THREAD

**Issue by JaimeChavarriaga** [hyperbox/hyperbox#34]
The project may include a `CONTRIBUTING.md` file with instructions for people interested on contributing to the project.
- The file may describe the branching model and some guidelines for issues, branches and pull requests.
- Creating the file/discussing this issue may help  new developers to start contributing the software.

The guideline may describe how to initialize the repositories. In addition, if the project adopts a branching model such as the [git-flow](http://nvie.com/posts/a-successful-git-branching-model/), it may include instructions to create features and bug-fixes using existing tools.

**Comment by maxidor** [comment]
Thank you for your contribution, but we are currently not interested into a `CONTRIBUTING.md` file and your specific contribution also does not fit our ways either. I'll close the PR also.
