### ISSUE TITLE
trying to reinstall 

### ISSUE THREAD

**Issue by crusher42** [hyperbox/hyperbox#37]
i need help i trying to reinstall on my server  from github install 
i have
 ```
rm -rf /opt/
```
and did the cit commads

**Comment by maxidorius** [comment]
Just re-run the install script

**Comment by crusher42** [comment]
Yes I know that but I set the user wrong by mistake
I need to know how to reinstall and set the user I forgot to say that last time

**Comment by maxidorius** [comment]
The install script should always prompt you for the user. Are you saying that is not the case?

**Comment by crusher42** [comment]
No it not asking it just installs and start the service it does say if I want to stop the service and overwrite the directory at /opt/hbod I think that's it

**Comment by maxidorius** [comment]
Can you try deleting that user too then, and see if you're prompted if you run the script again?

**Comment by crusher42** [comment]
cant delete user i set root how can i change it manually

**Comment by maxidorius** [comment]
Edit the `RUNAS` value in `/etc/init.d/hboxd`

**Comment by crusher42** [comment]
thx
