### ISSUE TITLE
VBox Compatibility Questions

### ISSUE THREAD

**Issue by tinjaw** [hyperbox/hyperbox#38]
Is VBox v 6.x in testing yet? If so, how test? Can I have both VBox v5 and v6 installed on a Windows 10 box?

**Comment by tinjaw** [comment]
Is VBox v 6.x in testing yet? If so, how test? Can I have both VBox v5 and v6 installed on a Windows 10 box?

**Comment by maxidorius** [comment]
It's not yet in testing. The current schedule is some time this month after we cleared more urgent priorities on our other projects. I've made #39 to keep track of the work. You can subscribe to it to get updates.
