### ISSUE TITLE
Cannot register current VMs for user

### ISSUE THREAD

**Issue by Johnnyreyman** [hyperbox/hyperbox#41]
I cannot register the current vms and are returned with this issue:
![image](https://user-images.githubusercontent.com/31798114/54976498-8a7aaf80-4f68-11e9-98ac-9d0b6b1300a5.png)
My server is Ubuntu 18.04 LTS
My Client PC is an Ubuntu 16.04-based distro

**Comment by maxidorius** [comment]
`Access denied` is your issue. You need to fix your VM permissions so they can be read by the hyperbox user.
