### ISSUE TITLE
Client will not launch 18.04

### ISSUE THREAD

**Issue by Johnnyreyman** [hyperbox/hyperbox#43]
The HBox Client 0.0.14 will not launch in Mint 19.1 (Ubuntu 18.04).

**Comment by maxidorius** [comment]
what is the output of `java -version` please?

**Comment by Srendi** [comment]
FYI: Without trying the release files, I compiled from source according to the steps in the readme on Xubuntu 18.04 64 bit and it works fine for connecting to localhost with Virtualbox 5.2
gavin@worker01:~$ java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.18.04.1-b03)
OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)

**Comment by maxidorius** [comment]
Fix with Release [v0.0.15](https://github.com/hyperbox/hyperbox/releases/tag/v0.0.15)
