### ISSUE TITLE
Hbox client on High Resolution displays

### ISSUE THREAD

**Issue by bsherwoodofdaptiv** [hyperbox/hyperbox#47]
My display is 3000x2000 (Microsoft Surface). I run at 200% scaling in Windows 10

Client UI doesn't seem to cope with this very well. See attached PNGimage.

Issue seems to be in table based elements and the side menu. Other tab's information seems able to layout nicely. See second image.

![hbox_client_ui_issue](https://user-images.githubusercontent.com/2326615/67615816-a9068a80-f785-11e9-850e-fccecdcaef2b.png)

![hbox_client_ui_okay](https://user-images.githubusercontent.com/2326615/67615818-ac017b00-f785-11e9-988c-aa7f3ed120d0.png)

**Comment by bsherwoodofdaptiv** [comment]
I found a band-aide workaround. Definitely not a fix, but a way for people to cope with it until a UI change can be made to deal with this.

In Window 10, your right click on the HyperBox.EXE executable and choose Properties.
Click on the Compatibility tab
Click on the 'change High DPI settings'
In the bottom section, CHECK 'Override......'  and choose 'System Enhanced'
See picture:

![hbox_client_ui_scaling_workaround](https://user-images.githubusercontent.com/2326615/67616075-38616d00-f789-11e9-8a61-65d83c927038.png)

**Comment by maxidorius** [comment]
Sorry for the delay answering this, and thank you for documenting the work around.
Hyperbox is using the Swing library which does not support High resolution, so nothing we can do about it in the current state.
