### ISSUE TITLE
Can't connect to hypervisor

### ISSUE THREAD

**Issue by grego31430** [hyperbox/hyperbox#50]
I have just install Hyperbox with a virtualbox 5.2, but when I try to connect to hypervisor the request failed.
From the log I see a problem with the webservice of virtualbox.
Any solution that I can use the XPCOM ?

**Comment by grego31430** [comment]
[hboxd.log](https://github.com/hyperbox/hyperbox/files/5497911/hboxd.log)
here is the log file when I try to connect

**Comment by maxidorius** [comment]
Hello @grego31430 - can you try the new release and re-open a new issue if it still doesn't work? Be sure to include the server log also! Thanks!
