### ISSUE TITLE
Error server install

### ISSUE THREAD

**Issue by scorpey** [hyperbox/hyperbox#51]
hi!

I have
Debian 10
 version "11.0.9.1" 2020-11-04
` sh hbox-server-0.0.15-linux_x64.run
Verifying archive integrity...  100%   All good.
Uncompressing Hyperbox Server  100%

#       # #       # ######### ######### #########  ########   ######  #       #
#       #  #     #  #       # #         #        # #       # #      #  #     #
#       #   #   #   #       # #         #        # #       # #      #   #   #
#########    # #    ######### ######### #########  ########  #      #    # #
#       #     #     #         #         #     #    #       # #      #   #   #
#       #     #     #         #         #      #   #       # #      #  #     #
#       #     #     #         ######### #       #  ########   ######  #       #

http://kamax.io/hbox/

Debian-based system detected
hboxd requires Java 1.6 or later.
An error occurred and the installation will now be cancelled. Check log file for more details: /var/log/hboxd-install.log
`
And log

`Installation start at 30-12-2020 @ 12:12
No parameters were given to the script
Debian-based system detected
Checking Java version
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-post-Debian-1deb10u2)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-post-Debian-1deb10u2, mixed mode, sharing)

hboxd requires Java 1.6 or later.
Aborting install
Installation finished at 30-12-2020 @ 12:12
`

**Comment by maxidorius** [comment]
@scorpey Will be fixed in the next release. Thank you for the report!
