### ISSUE TITLE
Help me, I'm running the game on a virtual machine and this error pops up

### ISSUE THREAD

**Issue by volcane5** [hyperbox/hyperbox#59]
What to do I use version 6.1.46 of the virtual machine, I run it and try to log into the game on it and this error pops up on the screenshot.I didn't understand what to do help
![Снимок экрана 2023-08-02 233120](https://github.com/hyperbox/hyperbox/assets/133363586/e91e7a0e-5f02-4cb6-98b8-aafd3a8d1ced)

**Comment by maxidorius** [comment]
Hello, your issue is with VirtualBox, not Hyperbox. Please contact them directly.
