### ISSUE TITLE
virtualbox error message

### ISSUE THREAD

**Issue by samet9999** [hyperbox/hyperbox#60]
![Ekran görüntüsü 2024-01-17 152004](https://github.com/hyperbox/hyperbox/assets/156913291/86810708-b763-4d29-acb4-3858059d7571)
virtualbox açılmıyor

**Comment by maxidorius** [comment]
Hello, this is not a Hyperbox problem, please contact the VirtualBox team.

**Comment by samet9999** [comment]
> Merhaba, bu bir Hyperbox sorunu değil, lütfen VirtualBox ekibiyle iletişime geçin.

türk müsün?

**Comment by samet9999** [comment]
> Merhaba, bu bir Hyperbox sorunu değil, lütfen VirtualBox ekibiyle iletişime geçin.

virtualbox ekibi nereden iletişime geçebilirim?

**Comment by maxidorius** [comment]
I've put your messages through a translator:
- I do not speak Turkish
- You can contact the VirtualBox team on the VirtualBox webiste, "Community" section: https://www.virtualbox.org/wiki/Community

**Comment by samet9999** [comment]
ok
