### ISSUE TITLE
Cannot list Hypervisors (io.kamax.hboxd.hypervisor.Hypervisor missing element version)

### ISSUE THREAD

**Issue by mribichich** [hyperbox/hyperbox#8]
Hi there, I'm trying to use the hyperbox, but when I try to connect to the hypervisor the window dialog comes empty.

I'm using:

windows **7 x64**
hyperbox **0.13**
java: **jre-8u101-windows-x64**
virtualbox: **VirtualBox-5.1.0-108711-Win** and also tried **VirtualBox-5.1.2-108956-Win**

![connect to hypervisor_2](https://cloud.githubusercontent.com/assets/5748554/17279997/cd182c04-575a-11e6-978c-8b139549a716.jpg)

Thanks!

The logs says this:

```
+==============================================================+
 Log start on 31/07/2016 @ 20:00:04           +
+==============================================================+
Hyperbox 0.0.13 - Java 1.8.0_101 Java HotSpot(TM) 64-Bit Server VM 25.101-b13 - Windows 7 6.1 amd64
2016.07.31-20:00:04.030 |      Info | Hyperbox Init Sequence started
2016.07.31-20:00:07.979 |      Info | Server ID: af244c84-0dc6-49a5-a406-b8ad4196abd3
2016.07.31-20:00:07.979 |      Info | Server Name: WIN-2TCHN0BRKF1
2016.07.31-20:00:08.900 |      Info | Refreshing modules...
2016.07.31-20:00:08.900 |      Info | Searching in C:\Program Files\Hyperbox\Server\modules for modules...
2016.07.31-20:00:08.900 |      Info | Attempting to add module with descriptor file: C:\Program Files\Hyperbox\Server\modules\vbox-4_2-ws.xml
2016.07.31-20:00:08.931 |      Info | Module ID vbox-4_2-ws (Virtualbox 4.2 WebService Connector) was successfully registered
2016.07.31-20:00:09.134 |      Info | Module ID vbox-4_2-ws (Virtualbox 4.2 WebService Connector) was autoloaded
2016.07.31-20:00:09.134 |      Info | Attempting to add module with descriptor file: C:\Program Files\Hyperbox\Server\modules\vbox-4_2-xpcom.xml
2016.07.31-20:00:09.149 |      Info | Module ID vbox-4_2-xpcom (VirtualBox 4.2 XPCOM Connector) was successfully registered
2016.07.31-20:00:09.648 |      Info | Module ID vbox-4_2-xpcom (VirtualBox 4.2 XPCOM Connector) was autoloaded
2016.07.31-20:00:09.648 |      Info | Attempting to add module with descriptor file: C:\Program Files\Hyperbox\Server\modules\vbox-4_3-ws.xml
2016.07.31-20:00:09.664 |      Info | Module ID vbox-4_3-ws (Virtualbox 4.3 WebServices Connector) was successfully registered
2016.07.31-20:00:09.992 |      Info | Module ID vbox-4_3-ws (Virtualbox 4.3 WebServices Connector) was autoloaded
2016.07.31-20:00:09.992 |      Info | Attempting to add module with descriptor file: C:\Program Files\Hyperbox\Server\modules\vbox-4_3-xpcom.xml
2016.07.31-20:00:09.992 |      Info | Module ID vbox-4_3-xpcom (VirtualBox 4.3 XPCOM Connector) was successfully registered
2016.07.31-20:00:10.054 |      Info | Module ID vbox-4_3-xpcom (VirtualBox 4.3 XPCOM Connector) was autoloaded
2016.07.31-20:00:10.054 |      Info | Attempting to add module with descriptor file: C:\Program Files\Hyperbox\Server\modules\vbox-5_0-ws.xml
2016.07.31-20:00:10.070 |      Info | Module ID vbox-5_0-ws (Virtualbox 5.0 WebService Connector) was successfully registered
2016.07.31-20:00:10.163 |      Info | Module ID vbox-5_0-ws (Virtualbox 5.0 WebService Connector) was autoloaded
2016.07.31-20:00:10.163 |      Info | Attempting to add module with descriptor file: C:\Program Files\Hyperbox\Server\modules\vbox-5_0-xpcom.xml
2016.07.31-20:00:10.179 |      Info | Module ID vbox-5_0-xpcom (Virtualbox 5.0 XPCOM Connector) was successfully registered
2016.07.31-20:00:10.226 |      Info | Module ID vbox-5_0-xpcom (Virtualbox 5.0 XPCOM Connector) was autoloaded
2016.07.31-20:00:10.226 |      Info | Attempting to add module with descriptor file: C:\Program Files\Hyperbox\Server\modules\vbox-5_1-ws.xml
2016.07.31-20:00:10.226 |      Info | Module ID vbox-5_1-ws (Virtualbox 5.1 WebService Connector) was successfully registered
2016.07.31-20:00:10.350 |      Info | Module ID vbox-5_1-ws (Virtualbox 5.1 WebService Connector) was autoloaded
2016.07.31-20:00:10.350 |      Info | Attempting to add module with descriptor file: C:\Program Files\Hyperbox\Server\modules\vbox-5_1-xpcom.xml
2016.07.31-20:00:10.366 |      Info | Module ID vbox-5_1-xpcom (Virtualbox 5.1 XPCOM Connector) was successfully registered
2016.07.31-20:00:10.397 |      Info | Module ID vbox-5_1-xpcom (Virtualbox 5.1 XPCOM Connector) was autoloaded
2016.07.31-20:00:10.397 |      Info | Finished refreshing modules.
2016.07.31-20:00:10.397 |      Info | No Hypervisor configuration found, skipping
2016.07.31-20:00:10.397 |      Info | Starting Front-ends
2016.07.31-20:00:10.538 |      Info | Kryonet connector is listening on port 45612
2016.07.31-20:00:10.538 |      Info | KryonetServerFront has started
2016.07.31-20:00:10.538 |      Info | Done starting Front-ends
2016.07.31-20:00:10.538 |      Info | -------> Hyperbox is running <-------
2016.07.31-20:00:24.734 |      Info | Conn #1 192.168.1.66 connected.
2016.07.31-20:00:27.636 | Exception | SessWT - Session #1470006024734 - Connection #1 | TaskManager
java.lang.annotation.IncompleteAnnotationException: io.kamax.hboxd.hypervisor.Hypervisor missing element version
    at sun.reflect.annotation.AnnotationInvocationHandler.invoke(Unknown Source)
    at com.sun.proxy.$Proxy3.version(Unknown Source)
    at io.kamax.hboxd.comm.io.factory.HypervisorIoFactory.getOut(HypervisorIoFactory.java:60)
    at io.kamax.hboxd.core.action.hypervisor.HypervisorList.run(HypervisorList.java:63)
    at io.kamax.hboxd.task.TaskManager$TaskWorker.execute(TaskManager.java:158)
    at io.kamax.hboxd.task.TaskManager.process(TaskManager.java:110)
    at io.kamax.hboxd.session.AbstractSession.run(AbstractSession.java:153)
    at java.lang.Thread.run(Unknown Source)
```

**Comment by maxidor** [comment]
Did you already have hyperbox installed before? or is this a clean install on the client AND server side?

**Comment by mribichich** [comment]
It is a clean install

I can try to uninstall everything and try again

**Comment by maxidor** [comment]
The location of the error is clear but I don't see what could be wrong - it's complaining about a missing piece of code which is actually there.

Please try to reinstall, yes. Make sure you delete the server installation directory before installing again and let's see what happens.

**Comment by mribichich** [comment]
It'll be great to have like a uninstall option in the Programs section.
because there is no easy way to do it

**Comment by mribichich** [comment]
I dont know if you know ir but you could use nssm, to create an installer.
it pretty cool and easy to use

**Comment by maxidor** [comment]
Normally there is an uninstall option with the Windows installer. We are using NSIS which provides it.
I'll double check on my end if it's there and how obvious it is.

**Comment by mribichich** [comment]
Thats it!

its showing something now

take a look at nssm or any other, you can control to uninstall a previous
version and intall the new one, start and stop a service, whatever.

thanks!

**Comment by maxidor** [comment]
Great! Fluke of the install, I'll see if I can reproduce it in a VM, but so far now clue what could be the cause.

**Comment by mribichich** [comment]
sorry I ment nsis. take a look, there is no option

[image: pasted1]

**Comment by maxidor** [comment]
I will. Thank you very much for your feedback and taking the time to report the issue, much appreciated

**Comment by mribichich** [comment]
I used the exe option. may that was it.

**Comment by mribichich** [comment]
Sorry I found another thing.

I tried to use the XPCOM connector and I got this error message:

VBoxManage was not found at C:\usr\lib\virtualbox\VBoxManage

It seems to be trying to find it in a linux path

I have virtualbox installed in the default path: C:\Program
Files\Oracle\VirtualBox

should I use xpcom o webservice?

**Comment by maxidor** [comment]
Only WebServices is possible on Windows, XPCOM is Linux only.
I need to hide that option in Windows, on the TODO list :)

**Comment by mribichich** [comment]
great thanks!!

**Comment by Axsimulate** [comment]
I'm having the same problem except the server is a headless Ubuntu Server and the client is Windows 7.
I've uninstalled and reinstalled Hyperbox on Windows to no avail.
Do I need to uninstall Hyperbox on Linux and if so, how do I uninstall it as is was not installed via apt-get install?

**Comment by maxidor** [comment]
The error actually happens on the server side, so yes, please reinstall the server part.
To uninstall it, simply delete the `/opt/hboxd` directory after stopping the service.

The link is quite obsolete in how to do it, many steps are unecessary now (like manually managing the vboxwebsrv part).
If you run the install, it will put an init.d script which can be called with any init daemon, including systemd:
`systemctl <action> hboxd` or `/etc/init.d/hboxd <action>`

**Comment by Axsimulate** [comment]
I stopped the service by typing systemctl stop hboxd
I removed the hboxd directory by typing sudo rm -rf /opt/hboxd
I reinstalled by typing  sudo sh hbox_server-latest-linux_amd64.run
I still have the same problem. Did I miss anything?

**Comment by maxidor** [comment]
Where did you download the installer? I have a feeling a link is obsolete somewhere...

**Comment by Axsimulate** [comment]
I don't remember. I thought is was from the link I posted. But apparently not. Whats the best link to d/l it?

**Comment by maxidor** [comment]
At the bottom of the [latest release page](https://github.com/hyperbox/hyperbox/releases/latest)

**Comment by Axsimulate** [comment]
Ah! got it! That worked! Thank you very much!!!

**Comment by maxidor** [comment]
Glad it did! So I just need to find out which link is broken where :)

**Comment by Axsimulate** [comment]
The link that worked for me was...
wget https://github.com/hyperbox/hyperbox/releases/download/0.0.13/hbox-0.0.13-linux_amd64-server.run

**Comment by maxidor** [comment]
yep. But there is an obsolete link somewhere that points to the wrong file (you can see the filename is different), just need to make sure that obsolete link is gone.

**Comment by irvintim** [comment]
The broken link is https://kamax.io/hbox/download/hbox_server-latest-linux_amd64.run, whic is referenced in the manual: https://kamax.io/hbox/manual/#il

**Comment by maxidor** [comment]
@irvintim thanks! will fix
